#.travis.yml
git:
  depth: 3

matrix:
  include:
    - language: ruby
      script: bundle exec jekyll build
      cache: bundler

    - language: node_js
      node_js: "node"
      script: node travis-script.js
      cache: npm
