[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy-Report-Only = "default-src 'self'; script-src 'self' https://assets.dcube.cloud https://assets.wogaa.sg https://www.google-analytics.com https://cdnjs.cloudflare.com https://va.ecitizen.gov.sg https://*.cloudfront.net; object-src 'none'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com/ https://*.cloudfront.net; img-src *; media-src *; frame-src 'none'; font-src *"